config/routes.rb
Garage::Application.routes.draw do
  root 'pages#landing_page'  

  devise_for :users
  resources :sales
  resources :pages

  get '/landing_page', to: 'pages#landing_page', as: :landing_page
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  get '/my_sales', to: 'pages#user_sales', as: :my_sales
  get '/my_items', to: 'pages#user_items', as: :my_items
  get '/my_transactions', to: 'pages#user_transactions', as: :my_transactions

  get '/sales/:sale_id/items/:id', to: "items#show"
  post '/sales/:sale_id/items', to: "items#create", as: :item_create
  delete '/sales/:sale_id/items/:id', to: "items#destroy", as: :item
  
  post '/sales/:sale_id/items/:id', to: "transactions#create", as: "transaction"
end

app/models/item.rb
class Item < ActiveRecord::Base

  has_attached_file :photo, :styles => { :large => "500x500#", :medium => "300x300>", :thumb => "200x200>" }, :default_url => "/images/:style/missing.jpg"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
 
  belongs_to :sale
  has_one :transaction
  
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  has_attached_file :photo, :styles => { :large => "500x500#", :medium => "300x300>", :thumb => "200x200>" } 
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  validates :title, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :zipcode, presence: true

  belongs_to :user
  has_many :items

  accepts_nested_attributes_for :items
  
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :user
  belongs_to :item

  validates :user_id, presence: true
  validates :seller_id, presence: true
  validates :item_id, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true         #User must have a name

  has_many :sales
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
 
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :phone) }
    end

    def after_sign_in_path_for(resource)
      '/dashboard'
    end

    def after_sign_up_path_for(resource)
      '/dashboard'
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :lookup, except: [:new]
 
  def new
    @item = Sale.find(params[:sale_id]).items.new
    respond_to do |format|
      format.html
      format.json { render :json => @item }
    end
  end

  def show
    @item = @sale.items.where(id: params[:id])[0]
  end

  def create
    @item = @sale.items.create item_params
    respond_to do |format|
      if @item.save
        format.html { redirect_to @sale }
        format.json { render :json => @item, status: :created, :location => 'nil' }
      else
        format.html
        format.json { render :json => @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sale.items.where(id: params[:id])[0].destroy!
    respond_to do |format|
      if Item.all.where(id: params[:id])[0] == nil
        format.html { redirect_to '/' }
        format.json { render :json => @sale, status: :no_content }
      end
    end
  end

private
  def lookup
    @sale = Sale.find(params[:sale_id])
  end
  
  def item_params
    params.require(:item).permit(:name, :description, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:landing_page]

  def landing_page
  end

  def dashboard
  end

  def user_sales
    @user_sales = current_user.sales
  end

  def user_items
    @user_sales = current_user.sales
  end

  def user_transactions
    @user_as_buyer_transactions = Transaction.where(user_id: current_user.id)
    @user_as_seller_transactions = Transaction.where(seller_id: current_user.id)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :lookup, only: [:edit, :show, :update, :destroy]

  def index
    @sales = Sale.all
    respond_to do |format|
      format.html
      format.json { render :json => { sales: @sales.as_json(include: :items) }, status: :ok } # if transaction_id == nil (?)
    end
    
    # respond_to do |format|
    #   @sales.each do |sale|
    #     items = sale.items.where(transaction_id: nil)
    #     format.json { render json: {"sales" => sale.as_json(include: (items: items.as_json) }, status: :ok } # if transaction_id == nil (?)
    #   end
    # end
  end

  def new
    @sale = Sale.new
    respond_to do |format|
      format.html
      format.json { render :json => @sale }
    end
  end

  def create
    @sale = current_user.sales.create sale_params
    respond_to do |format|
      if @sale.save!
        format.html { redirect_to @sale } # redirect user to ? after garage sale create
        format.json { render :json => @sale , status: :created }
      else
        format.html { redirect_to '/sales/new', status: :unprocessable_entity }
        format.json { render :json => @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    @sale.update sale_params
    respond_to do |format|
      if @sale.save
        format.html 
        format.json { render :json => @sale, notice: "sucessful update." }
      else
        format.html
        format.json { render :json => @sale.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to '/'} # redirect user to ? after garage sale destroy
      format.json { render :json => @sale, status: :no_content }
    end
  end

  # rescue_from ActionController::ParameterMissing, :only => :create do |err|
  #   respond_to do |format|
  #     format.json {render :json  => {:error => err.message}, :status => 422}
  #   end
  # end

private
  def lookup
    @sale = Sale.find(params[:id])
  end

  def sale_params
    params.require(:sale).permit(:address, :city, :zipcode, :date, :time_start, :time_end, :title, :description, :photo, items_attributes: [:name,:description,:price])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def create
    item_id = params[:id]
    sale_id = params[:sale_id]
    sale = Sale.find_by_id(sale_id)

    transaction = nil
    if sale
      item = sale.items.find_by_id(item_id)
      if item
        if sale.user_id != current_user.id
          seller_id = sale.user_id
          transaction = Transaction.new(user_id: current_user.id, seller_id: seller_id, item_id: item_id)
        end
      end
    end

    if transaction && transaction.save
      item.transaction_id = transaction.id
      if item.save
        flash[:sucess] = "item purchased"
        #sidekiq emailer
        redirect_to "/sales/#{sale_id}"
      else
        flash[:error] = "transaction failed"
        redirect_to sale
      end 
    else
      flash[:error] = "transaction failed"
      redirect_to sales_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #including the following methods from devise so sign-in/sign-out are available anywhere
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def after_sign_in_path_for(resource)
    '/user_sales'
  end
end

app/views/items/show.html.erb
<div>
  <li><%= @item.name %> <%= number_to_currency(@item.price) %> <%= @item.description %></li>
 		<%= image_tag @item.photo.url(:medium) %>
  	<%= @sale.date %>  <%= @sale.title %>  <%= @sale.city %>  <%= @sale.zipcode %>  <%= @sale.description %>  <%= @sale.time_start %>  <%= @sale.time_end %>  <%= @sale.user.email unless @sale.user.blank? %><%# =image_tag sale.photo_file_name.url(:thumb) %>
	  <div>
	  	<% if @item.transaction_id == nil %>
	    	<%= button_to 'confirm', "/sales/#{@sale.id}/items/#{@item.id}" %> <!--  posts to transactions#create -->
	  	<% end %>
	  </div>
	  <div>
	  	<% if @item.transaction_id == nil %>
	    	<%= button_to 'cancel', "/sales/#{params[:sale_id]}/", method: :get %>
	  	<% end %>
	  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <a class="navbar-brand" href="/sales">Garage Sales</a>
    <% if current_user != nil %>
      <a class="navbar-brand" href="/dashboard">Dashboard</a>
    <%end%>
  </div>
  <div class="navbar-header navbar-right">
    
    <% if signed_in? %>
      <p class="navbar-text">
        <%= link_to "Hello, #{current_user.name}" , edit_user_registration_path, :method => :get %>
      </p>
      <p class="navbar-text">
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete%>
      </p>
    <% else %>
      <div id="sign-in">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <%= f.email_field :email, autofocus: true, :placeholder => "Email Address" %>
          <%= f.password_field :password, autocomplete: "off", :placeholder => "Password" %>
          <%=f.submit "Sign in" %>
        <% end %>
      </div>
    <% end %>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Garage</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>
  
  <%= yield %>

</body>
</html>

app/views/pages/_nav.html.erb
<%= button_to "New Garage Sale", {controller: :sales, action: :new}, :method => :get,  class: "btn btn-sm btn-primary" %> <br>
<%= link_to "My Garage Sales", '/my_sales'%> <br>
<%= link_to "My Items", '/my_items'%> <br>
<%= link_to "My Transactions", '/my_transactions' %> <br>

app/views/pages/dashboard.html.erb
<div class="row">
  <div class="col-md-3 dashnav">
    <%= render :partial => 'nav' %> 
  </div>
  <div class="col-md-7">

  <h2>Welcome to your Dashboard</h2>
</div>
</div>

app/views/pages/index.html.erb
<h1>Welcome to Garage Sales</h1>

  <%= button_to "Sign-Up", '/users/sign_up', :method => :get %> 

app/views/pages/landing_page.html.erb
<div class="background">
  <h1 id="landing">Welcome to Garage Sales</h1>
  <%= link_to "Sign-Up", '/users/sign_up', class: "btn btn-lg btn-success" %> 
</div>

app/views/pages/user_items.html.erb
<div class="row">
  <div class="col-md-3 dashnav">
    <%= render :partial => 'nav' %> 
  </div>
  <div class="col-md-7">

    <h2>My Items</h2>

    <% if @user_sales == [] %>
      <p>You don't have any Items</p>
    <%end%>

    <ul>
      <% @user_sales.each do |sale| %>
      <li><h4><b><%= sale.title %></b> <%= sale.date %></h4></li>
        <ul>
        <% sale.items.each do |item|%>
        <li><b><%= item.name %></b>  <%= number_to_currency(item.price) %><br>
        <%= item.description %>
        <%= link_to('Delete', "/sales/#{sale.id}/items/#{item.id}", :method => :delete, :confirm => 'Are you sure?', class: "btn btn-xs btn-danger")  %>
        </li>
      <% end %>
    </ul>
      <% end %>

    </ul>
  </div>
</div>

app/views/pages/user_sales.html.erb
<div class="row">
  <div class="col-md-3 dashnav">
    <%= render :partial => 'nav' %> 
  </div>
  <div class="col-md-7">
    <h2>My Garage Sales</h2>

    <% if @user_sales==[] %>
      <p>You don't have any Garage Sales</p>
    <%end%>

    <ul>
      <% @user_sales.each do |sale| %>
        <li><b><%= sale.title %></b> - <%= sale.address %>,<%= sale.city%> <%= sale.zipcode %><br>
          When: <%= sale.date %> From <%= sale.time_start %> to <%= sale.time_end %><br>
          Description: <%= sale.description %>   
          <%= link_to('Delete', sale, :method => :delete, :confirm => 'Are you sure?', class: "btn btn-xs btn-danger")  %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/user_transactions.html.erb
<div class="row">
  <div class="col-md-3 dashnav">
    <%= render :partial => 'nav' %> 
  </div>
  <div class="col-md-7">
    
    <h2>Transactions</h2>
    <ul>
      <% if @user_as_seller_transactions == [] %>
        <li>You have not sold any items.</li>
      <% else %>
        <li>Items Sold:</li>
          <ul> 
            <% @user_as_seller_transactions.each do |transaction| %>
              <li><%= transaction.item.name %>, $<%= transaction.item.price %></li>
                  <ul>
                    <li>Buyer Name: <%= transaction.user.name%> Phone: <%= transaction.user.phone %></li>
                    <li>Email: <%= mail_to transaction.user.email, transaction.user.email %></li>
                  </ul>
              </li>
            <% end %> 
          </ul>
      <% end %>
      
      <% if @user_as_buyer_transactions == [] %>
        <li>You have not purchased any items.</li>  
      <% else %>
        <li>Items Purchased:</li>
          <ul>
            <% @user_as_buyer_transactions.each do |transaction| %>
              <% seller = User.find(transaction.seller_id) %>
              <% sale = Sale.find(transaction.item.sale_id) %>
                <li><%= transaction.item.name %> <em>$<%= transaction.item.price %></em><br>
                    <%= transaction.item.description %><br>
                      <ul>
                        <li>Seller Name: <%= seller.name %>, Phone: <%= seller.phone %></li>
                        <li>Email: <%= mail_to seller.email, seller.email %></li>
                          <ul>
                            <li>Title: <%= sale.title %><em> (<%= sale.date %>)</em></li>
                            <li>Address: <%= sale.address %>, <%= sale.city %>, <%= sale.zipcode %></li>
                            <li>From: <%= sale.time_start %> To: <%= sale.time_end %></li>
                            <li>Description: <%= sale.description %></li>
                          </ul>
                      </ul>
                </li>
            <% end %>
          </ul>
      <% end %>
    </ul> 
  
  </div>
</div>

app/views/sales/index.html.erb
<div>
   <% @sales.each do |sale| %>
        <li><%= image_tag sale.photo.url(:thumb) %> <%= link_to sale.title, sale_path(sale) %> <%= sale.address %>
          <%= sale.city %>
         <%# =image_tag sale.photo_file_name.url(:thumb) %>
          <%= sale.description %>
          <%= sale.date %>
        </li><br>
  <% end %>
</div>

app/views/sales/new.html.erb
<%= form_for @sale, :multipart => true do |f| %>
  
  <div>  
    <%= f.label :title %>  
    <%= f.text_field :title, placeholder: "title" %>  
  </div>  
  <div>  
    <%= f.label :address %>  
    <%= f.text_field :address, placeholder: "address" %>  
  </div>  
  <div>  
    <%= f.label :city %>  
    <%= f.text_field :city, placeholder: "city" %>  
  </div>  
  <div>  
    <%= f.label :zipcode %>  
    <%= f.text_field :zipcode, placeholder: "zipcode" %>  
  </div>  
  <div>  
    <%= f.label :description %>  
    <%= f.text_field :description, placeholder: "description" %>  
  </div>  
  <div>  
    <%= f.label :date %>  
    <%= f.text_field :date, placeholder: "Date" %>  
  </div>
  <div>  
    <%= f.label :time_start %>  
    <%= select_tag "sale[start_time]", options_for_select((9..21).map {|item| time = item% 12; item > 11? time = time.to_s + "am": time = time.to_s+ "pm"; [time,item] }) %>
  </div>
  <div>  
    <%= f.label :time_end %>  
    <%= select_tag "sale[end_time]", options_for_select((9..21).map {|item| time = item% 12; item > 11? time = time.to_s + "am": time = time.to_s+ "pm"; [time,item] }) %>
  </div>
    <%= f.file_field :photo %>
  <div id="items">
    <div>
      <%= f.fields_for :items, @sale.items.build do |b| %>
        <%= b.text_field :name, placeholder: "name" %>
        <%= b.text_field :description, placeholder: "description" %>
        <%= b.text_field :price, placeholder: "price" %>
        <button class="new_sale_item"> Add Item</button>
        <%= b.file_field :photo %>
      <% end  %>
    </div>
  </div>

  <%= f.submit "create sale" %> 
<% end %>
<script type="text/javascript">
    var count = 1;
  $(".new_sale_item").click(function(evt){
      evt.preventDefault();
      console.log("clicked");

      var name = '<input id="sale_items_attributes_' + count + '_name" name="sale[items_attributes][' + count + '][name]" placeholder="name" type="text"> ';

      var describe = '<input id="sale_items_attributes_' + count + '_description" name="sale[items_attributes][' + count + '][description]" placeholder="description" type="text"> ';

      var price = '<input id="sale_items_attributes_' + count + '_price" name="sale[items_attributes][' + count + '][price]" placeholder="price" type="text"> ';

      var file = '<input id="sale_items_attributes_' + count + '_photo" name="sale[items_attributes][' + count + '][photo]" type="file"> ';

      whole = "<div>"+ name + describe + price + file +"</div>";
      $("#items").prepend(whole);
      
      count++;
      console.log(count);

    });
</script>

app/views/sales/show.html.erb
<div>
  <% @sale.items.each do |item| %>
  	<% if item && item.transaction_id == nil %> <!-- does not list items that have been sold -->
    	<li><%= image_tag item.photo.url(:thumb) %> <%= link_to item.name, "/sales/#{@sale.id}/items/#{item.id}" %> $<%= item.price %></li>
  	<% end %>
  <% end %>

  <%= @sale.date %>  <%= @sale.title %>  <%= @sale.city %>  <%= @sale.zipcode %>  <%= @sale.description %>  <%= @sale.time_start %>  <%= @sale.time_end %>  <%= @sale.user.email unless @sale.user.blank? %> <%# =image_tag sale.photo_file_name.url(:thumb) %>

  <%= image_tag @sale.photo.url(:medium) %><br>
 </div>